name: K2P

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
    branches: 
      - cloud-build
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/77160860/padavan-4.4.git /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/
    - name: Build Firmware
      env:
        TNAME: K2P
      run: |
        cd /opt/rt-n56u/trunk
        if [ ! -f configs/templates/$TNAME.config ] ; then
        echo "configs/templates/$TNAME.config not found "
        exit 1
        fi
        cp -f configs/templates/$TNAME.config .config
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
        ################################################################################################
        # Delete the configuration items first!
        ################################################################################################
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MENTOHUST/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SSSERVER/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ADBYBY/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPC/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPS/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TUNSAFE/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ALIDDNS/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMARTDNS/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SRELAY/d' .config
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
  
        
        ######################################################################
        # Update the configuration items
        ######################################################################
        echo "CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_SSOBFS=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_ADBYBY=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_SRELAY=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_XRAY=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_DDNSTO=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_ALDRIVER=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_ZEROTIER=n" >> .confi
        echo "CONFIG_FIRMWARE_INCLUDE_ALIDDNS=n" >> .config    
        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME=y" >> .config   
        
        ##QOS & CPU Overclocking##
        echo "CONFIG_FIRMWARE_INCLUDE_SQM=y" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_OC=n" >> .config
        echo 'CONFIG_FIRMWARE_MT7621_OC="0x362"' >> .config # 1000Mhz=0x312 1100Mhz=0x362 1120Mhz=0x372 1200Mhz=0x3B2

        sudo ./clear_tree
        sudo ./build_firmware_modify $TNAME 0
        sudo mv -f images/*.trx /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: K2P
        path: /opt/images
